----------------------
-- <procedure>
-- Sistema de traduções
-- @Traduz o jogo para outras linguas.
----------------------
translations = {
     br = {  -- br = Brasil = Pt_br = Português brasil.
        welcome = "Bem-vindo ao #Wizard. Utilize os atalhos: H [Help], P [Perfil], T [Atualizações]",
        tab_profile = "Perfil",
        tab_League = "Clã",
        tab_Howtoplay = "Como jogar?",
        tab_LettersMissions = "Cartas/Missões",
        tab_help = "For more information press H",
        tab_yourgems = "Suas Gemas",
        tab_bank = "Banco",
        tab_requiredXP = "XP Requerido",
        tab_potions = "Poções",
        tab_trunk  = "Baú",
        tab_title = "Titulo",
        tab_Level = "Nivel",
        tab_GoldCoins = "Moedas de ouro",
        tab_gems = "Gemas",
        tab_havegems = "Você não tem gemas suficientes para completar a compra.",
        tab_LevelNext = "Você agora é nível",
        tab_buy = "Comprar",
        tab_tavern = "Taberna",
        tab_bookspell = "Livro de encantamento",
        tab_mypotions = "Minhas poções",
        tab_inventory = "Inventario",
        tab_classe = "Classe Atual",
        tab_victories = "Vitórias",
        tab_teamRed = "Você é um bruxo Vermelho!",
        tab_teamBlue = "Você é um bruxo Azul!",
        tab_wizardRed = "Bruxos vermelhos",
        tab_wizardBlue = "Bruxos Azuis",
        tab_helpStarGame1 = "<font size='14'><b><i>«Como jogar?»</i></b> Você é o aprendiz de feiticeiro e deve passar por obstáculos, desafios e armadilhas com sua equipe. Você e sua equipe deve lutar contra a equipe opondo-se e sendo o último vivo antes do final do jogo. \n<p align='center'><b>Correr, lutar e vencer! Tornar-se o bruxo todo-poderoso.<p></b></font>",
        tab_helpStarGame2 = "<font size='15'><i>Livro de mágicas:</i>\n<b>livros especiais que liberam as classes e novos poderes na loja.</b></font>",
        tab_helpStarGame3 = "<font size='14'><i>Cartas/missões:</i>\n<b>quando sua classe chegar ao limite de bônus, você recebe uma carta com missões, para a conquista de uma nova classe. E novos clãs.</b></font>",
        close = "Fechar",
    },
    
    en = { -- en = English = Inglês
        welcome      = "Welcome to #Wizard. Use the shortcuts: H [Help], P [Profile], T [Updates]",
        tab_profile  = "Profile",
        tab_League = "Clain",
        tab_Howtoplay ="How to play?",
        tab_LettersMissions = "Letters/Missions",
        tab_help = "For more information press H",
        tab_yourgems = "Your Gems",
        tab_bank     = "Bank",
        tab_requiredXP = "Required XP",
        tab_potions     = "Potions",
        tab_trunk  = "Trunk",
        tab_title = "Title",
        tab_Level = "Level",
        tab_GoldCoins = "Gold coins",
        tab_gems = "Gems",
        tab_havegems = "You don't have enough gems to complete the purchase.",
        tab_LevelNext = "You are now level",
        tab_buy = "Buy",
        tab_tavern = "Tavern",
        tab_bookspell = "SpellBook",
        tab_mypotions = "My potions",
        tab_inventory = "Inventory",
        tab_classe = "Current class",
        tab_victories = "Victories",
        tab_teamRed = "You are a wizard Red!",
        tab_teamBlue = "You are a wizard Blue!",
        tab_wizardRed = "Won as Red Wizards",
        tab_wizardBlue = "Won as Blue Wizards",
        tab_helpStarGame1 = "<font size='14'><b><i>«How to play?»</i></b>You're the sorcerer's apprentice and must pass by obstacles, challenges and pitfalls with your team. You and your team must battle against the opposing team and being the last living before the end of the game. \n<p align='center'><b>Run, fight and win! To become the all-powerful Wizard.<p></b>",
        tab_helpStarGame2 = "<font size='15'><i>SpellBook:</i>\n<b>special books that release classes and new powers in the store.</b></font>",
        tab_helpStarGame3 = "<font size='14'><i>Letters/missions:</i>\n<b>When your class get to the bonus limit, you receive a letter with missions, to the conquest of a new class.</b></font>",
        close = "<p align='center'>Close", -- ah é que eu estava com preguiça e por em tudo vou remover.
    }
}
